apiVersion: v1
kind: Template
metadata:
  name: hello-template
  annotations:
    description: "Description"
    iconClass: "icon-hello"
    tags: "hello,test"
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: hello-openshift
    name: hello-openshift
  spec:
    containers:
    - image: openshift/hello-openshift
      name: hello-openshift
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
        privileged: false
        procMount: Default
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /tmp
        name: tmp
        readOnly: true
    dnsPolicy: ClusterFirst
    restartPolicy: Always
    volumes:
    - emptyDir: {}
      name: tmp
  status: {}
parameters:
- description: Password used for Redis authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: REDIS_PASSWORD
labels:
  hello: master

