---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedServiceAccount
metadata:
  name: pacman
spec:
  placement:
    clusterSelector:
      matchLabels:
        cluster: available
  template:
    metadata:
      labels:
        name: pacman
